# Generated by Django 4.2.1 on 2023-05-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_to_recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myfood',
            name='number',
            field=models.IntegerField(default=1, verbose_name='個数'),
        ),
        migrations.AlterField(
            model_name='myfood',
            name='food',
            field=models.CharField(max_length=50, verbose_name='食材'),
        ),
    ]
