# Generated by Django 4.2.1 on 2023-05-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_to_recipe', '0002_myfood_number_alter_myfood_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfood',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
