# Generated by Django 4.2.1 on 2023-05-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_to_recipe', '0003_alter_myfood_createddate_alter_recipe_createddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfood',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='日時'),
        ),
    ]
